### ISSUE TITLE
Task 4

### ISSUE THREAD

**Issue by Soapony** [csci3250-2019/project-team-e#10]
Please do Task 4
@tom0034 @kennydc822 @pohchaichon @kayuior @wbwuta  @wing0114

**Comment by yuchitoto** [comment]
**Pls do task 4**
[Task 4 url here](https://github.com/csci3250-2019/project-team-e/blob/master/issues/task4.md)
And pls **ASSIGN** yourself here

**Comment by yuchitoto** [comment]
Done

**Comment by unitSphere** [comment]
Added my part of C code.

**Comment by unitSphere** [comment]
Now it is up to date.

**Comment by kennydc822** [comment]
Added my part, waiting for someone to help me check the code.
