### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by Soapony** [csci3250-2019/project-team-e#11]
Plase also do Task 5.
@tom0034 @kennydc822 @pohchaichon @kayuior @wbwuta @wing0114

**Comment by yuchitoto** [comment]
**Pls do task 5**
[Task 5 url here](https://github.com/csci3250-2019/project-team-e/blob/master/issues/task5.md)
And **ASSIGN** yourself here

**Comment by rubyluby** [comment]
there is some one haven't add in the group and try to add in...

**Comment by yuchitoto** [comment]
Seems to be completed
