### ISSUE TITLE
Pls add your 11551XXXXX.md in _stu

### ISSUE THREAD

**Issue by Soapony** [csci3250-2019/project-team-e#8]
Please include your own SID.md file under the contributor
@tom0034 @kennydc822 @pohchaichon @kayuior @yuchitoto

**Comment by Soapony** [comment]
@wbwuta  @wing0114

**Comment by yuchitoto** [comment]
For newcomers, please **add** your **11551XXXXX.md** in *_stu*.
[Formal Sample](https://github.com/csci3250-2019/project-team-e/blob/master/_stu/1155000000.md)

**Comment by yuchitoto** [comment]
You may also add some extra block of code in [code.c](https://github.com/csci3250-2019/project-team-e/blob/master/code.c)
